### ISSUE TITLE
Design Docs Review - Sample State

### ISSUE THREAD

**Issue by jliversi** [alextongme/noteworthy#2]
Really solid work on your sample state, only a few notes:
- [x] Change all snake_case to camelCase
- [x] Can you tag users on evernote? If not, remove the array of user_tag_ids under users.
- [x]  Notes can only be in one notebook, so they should store a single `notebookId` as opposed to an array.

**Comment by tongsalex** [comment]
hey josh, 

- I put the array of user_tag_ids to save which tags belong to which user. should i do this a different way? or are all 3 of those user arrays unnecessary on the sample state since it would have only fetched the logged in users data?
